### ISSUE TITLE
Add join and quit messages

### ISSUE THREAD

**Issue by lokka30** [Snowiiii/Pumpkin#188]
- [x] I've searched existing issues and couldn't find a duplicate.

**Is your feature request related to a problem? Please describe.**
- Pumpkin currently doesn't have join and quit messages.

**Describe the solution you'd like**
- Join message
  - Will position in `client_packets.rs`, at the top of `finish_login`, above where we send them the success packet.
- Quit message
  - I can't find where to put this, please could a maintainer advise
- Kick log message
  - Only an INFO log message to note that a player was kicked.

**To-do list**
- [x] Maintainers approve idea
- [x] Contributor indicates good place to handle the quit message code; edit above
- [x] Started work on a PR (linked to issue).
