### ISSUE TITLE
Add check if the server is full

### ISSUE THREAD

**Issue by lokka30** [Snowiiii/Pumpkin#189]
- [x] I've searched existing issues and couldn't find a duplicate.

**Is your feature request related to a problem? Please describe.**
- Players can join if the server is full

**Describe the solution you'd like**
- Add a check in `client_packet.rs`, after online mode authentication is done and after uuid/username duplicates checking is done. So in current master, around line 181.

**To-do**
- [ ] Maintainer likes idea
- [ ] @lokka30 started work on PR
